**

!Psi0/
!Psi0/src/
!Psi0/src/**
!Psi0/scripts/
!Psi0/scripts/**

!SIMPLE/
!SIMPLE/src/
!SIMPLE/src/**
!SIMPLE/docker/
!SIMPLE/docker/simple_holobrain/
!SIMPLE/docker/simple_holobrain/**

!robo_orchard_lab/
!robo_orchard_lab/robo_orchard_lab/
!robo_orchard_lab/robo_orchard_lab/**
!robo_orchard_lab/holomotion_tokenizer/
!robo_orchard_lab/holomotion_tokenizer/**
!robo_orchard_lab/scripts/
!robo_orchard_lab/scripts/**
!robo_orchard_lab/projects/
!robo_orchard_lab/projects/__init__.py
!robo_orchard_lab/projects/holobrain_internal/
!robo_orchard_lab/projects/holobrain_internal/common/
!robo_orchard_lab/projects/holobrain_internal/common/**
!robo_orchard_lab/projects/holobrain_internal/lightwheel/
!robo_orchard_lab/projects/holobrain_internal/lightwheel/**
!lw_benchhub/
!lw_benchhub/third_party/
!lw_benchhub/third_party/pytorch3d/
!lw_benchhub/third_party/pytorch3d/**

**/.git/**
**/__pycache__/**
**/*.pyc
**/*.pyo
**/.pytest_cache/**
